### ISSUE TITLE
CSS

### ISSUE THREAD

**Issue by KVonGit** [KVonGit/quest-compiler#9]
The style doesn't match the style in the Quest player.

The background color, a couple of the panes color (meaning the text color), and other stuff with link colors sometimes.

The panes are off, like the tables don't line up, and the second object in the place and objects pane has text you can't see and it's over to the right of the first object.

Probably need to check all the elements' class and id names against whatever the functions are thinking their names are. I feel that's the issue with most of this, but that's pure conjecture.

**Comment by KVonGit** [comment]
Thanks to Raist, quite a few missing CSS sheets have now been added to the unofficial release.

Things look much better, but there are still a few wrinkles to iron out.

**Comment by KVonGit** [comment]
Found one issue in style.css concerning the panes.

```css
.ui-accordion-header {
    background:black !important;
    border: 1px solid gray !important;
    padding: 3px !important;
}
```

---
That's what sets the compass label and places and objects label's stuff.

I added a line to style.css in my test game folder to make the text white, just to get things where you can see them with default settings.

```css
.ui-accordion-header {
    background:black !important;
	color:white !important;
    border: 1px solid gray !important;
    padding: 3px !important;
}
```

---
![image](https://github.com/user-attachments/assets/7109b809-2fb0-47bf-bb5f-70ae296ebca1)
